project_id = "eocmkehkesqrkrmgovct"

[functions.explain-word]
verify_jwt = false

[functions.detect-jargon-batch]
verify_jwt = false

[functions.elevenlabs-scribe-token]
verify_jwt = false

[functions.analyze-jargon]
verify_jwt = false